import Head from 'next/head'
import { Inter } from '@next/font/google'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='hidden sm:flex flex-col p-2 xl:items-start fixed h-full'>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className='flex min-h-screen max-w-7xl mx-auto'>

        {/** Side bar */}
        <Sidebar />
        {/** Feed     */}
        {/** Widgets  */}
        {/** Modal    */}

      </main>
    
    </div>
  )
}
